baseURL = ""
title = "Bernard-ML<a/b>"
copyright = "Copyright © 2008–2020, Steve Francia and the Hugo Authors; all rights reserved."
paginate = 2
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
googleAnalytics = "UA-XXXX"
DisqusShortname = ""
theme = "hugo-theme-chunky-poster"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "HOME"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "about"
    name = "ABOUT"
    url = "/about/"
    weight = 8
  [[menu.main]]
    identifier = "thoughts"
    name = "THOUGHTS"
    url = "/categories/thoughts/"
    weight = 3   
  [[menu.main]]
    identifier = "analytics"
    name = "ANALYTICS"
    url = "/categories/analytics/"
    weight = 4  
  [[menu.main]]
    identifier = "digitalmarketing"
    name = "DIGITAL MARKETING"
    url = "/categories/digitalmarketing/"
    weight = 4 


[taxonomies]
category = "categories"
tag = "tags"
series = "series"
author = "authors"

[params]
  author = "Bernard Yeo"
  description = "Analytics, Digital Marketing, Happy Stuffs"
  homepageImage = "/images/homepage-image.jpg"
  share = true
  showLanguageSwitcher = false

  # Custom CSS and JS. Relative to /static/css and /static/js respectively.
  customCSS = []
  customJS = []

  [params.social]
    rss = false
    email = "bernardyk.yeo@gmail.com"
#    facebook = "https://facebook.com"
    twitter = "https://twitter.com/byeothoughts"
    linkedin = "https://www.linkedin.com/in/bernardyk-yeo/"
#    stack-overflow = "https://stackoverflow.com"
#    instagram = "https://stackoverflow.com"
    github = "https://github.com/bernard-mlab?tab=repositories"
#    weibo = "https://www.weibo.com"
#    medium = "https://medium.com"
#    pinterest = "https://pinterest.com"
#    reddit = "https://reddit.com"
#    gitlab = "https://gitlab.com"
#    mastodon = "https://mastodon.social"
#    keybase = "https://keybase.io/"

  [params.prismJS]
    enable = true
    theme = "okaidia"

  [params.commento]
    enable = false
    url = "https://commento.io"

[markup]
  [markup.highlight]
    codeFences = false

[services]
  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
