backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  
media_folder: "static/uploads" # Media files will be stored in the repo under static/uploads
public_folder: "uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/post"
    create: true
    slug: "{{year}}-{{month}}-{{slug}}"
    fields:
      - {label: "Draft", name: "draft", widget: "boolean", required: true, default: true}
      - {label: "Publish Date", name: "date", widget: "datetime", required: true}
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Summary", name: "summary", widget: "string", required: false}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Categories", name: "categories", widget: "list", required: true}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Authors", name: "authors", widget: "list", required: true, default: ["Bernard Yeo"]}
      - {label: "Body", name: 'body', widget: 'markdown'}
